apps/account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm

app_name = "account"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="account/login.html", form_class=UserLoginForm
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page="/account/login/"),
        name="logout",
    ),
    path("register/", views.AccountRegister.as_view(), name="register"),
    path(
        "activate/<slug:uidb64>/<slug:token>/", views.account_activate, name="activate"
    ),
    path("reactivate/", views.AccountReactivate.as_view(), name="reactivate"),
    path(
        "reactivate_confirm/<slug:uidb64>/<slug:token>/",
        views.account_activate,
        name="reactivate_confirm",
    ),
    # password rest
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="account/password_reset/password_reset_form.html",
            success_url="password_reset_email_confirm",
            email_template_name="account/password_reset/password_reset_email.html",
            form_class=PwdResetForm,
        ),
        name="pwdreset",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="account/password_reset/password_reset_confirm.html",
            success_url="/account/password_reset_complete/",
            form_class=PwdResetConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/password_reset_email_confirm/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_complete/",
        TemplateView.as_view(template_name="account/password_reset/reset_status.html"),
        name="password_reset_complete",
    ),
    # dashboard
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("profile/edit/", views.EditDetailsView.as_view(), name="edit_details"),
    path("profile/delete_user/", views.DeleteUser.as_view(), name="delete_user"),
    path(
        "profile/delete_confirm/",
        TemplateView.as_view(template_name="account/dashboard/delete_confirm.html"),
        name="delete_confirmation",
    ),
    # Address
    path("addresses/", views.AddressView.as_view(), name="addresses"),
    path("add_address/", views.AddAddress.as_view(), name="add_address"),
    path("addresses/edit/<slug:id>/", views.EditAddress.as_view(), name="edit_address"),
    path("addresses/delete/<slug:id>/", views.DeleteAddress.as_view(), name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.SetDefaultView.as_view(), name="set_default"),
    # Wish List
    path("wishlist", views.Wishlist.as_view(), name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.WishlistAdd.as_view(), name="user_wishlist"),
    # orders
    path('orders', views.UserOrders.as_view(), name='orders')
]

apps/basket/urls.py
from django.urls import path

from . import views

app_name = "basket"

urlpatterns = [
    path("", views.BasketSummary.as_view(), name="basket_summary"),
    path("add/", views.BasketAdd.as_view(), name="basket_add"),
    path("update/", views.BasketUpdate.as_view(), name="basket_update"),
    path("delete/", views.BasketDelete.as_view(), name="basket_delete"),
]

apps/store/urls.py
from django.urls import path
from django.urls.conf import include

from . import views

app_name = "store"

urlpatterns = [
    path("", views.AllProducts.as_view(), name="store_home"),
    path("<slug:slug>", views.ProductDetail.as_view(), name="product_detail"),
    path(
        "shop/<slug:category_slug>/", views.CategoryList.as_view(), name="category_list"
    ),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("basket/", include("basket.urls", namespace="basket")),
    path("account/", include("account.urls", namespace="account")),
    path("checkout/", include("checkout.urls", namespace="checkout")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/store/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from mptt.models import MPTTModel, TreeForeignKey
from django.conf import settings


class Category(MPTTModel):
    """
    Category Table implimented with MPTT.
    """

    name = models.CharField(
        verbose_name=_("Category Name"),
        help_text=_("Required and unique"),
        max_length=255,
        unique=True,
    )
    slug = models.SlugField(
        verbose_name=_("Category safe URL"), max_length=255, unique=True
    )
    parent = TreeForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True, related_name="children"
    )
    is_active = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ["name"]

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def get_absolute_url(self):
        return reverse("store:category_list", args=[self.slug])

    def __str__(self):
        return self.name


class ProductType(models.Model):
    """
    ProductType Table will provide a list of the different types
    of products that are for sale.
    """

    name = models.CharField(
        verbose_name=_("Product Name"),
        help_text=_("Required"),
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Product Type")
        verbose_name_plural = _("Product Types")

    def __str__(self):
        return self.name


class ProductSpecification(models.Model):
    """
    The Product Specification Table contains product
    specifiction or features for the product types.
    """

    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    name = models.CharField(
        verbose_name=_("Name"), help_text=_("Required"), max_length=255
    )

    class Meta:
        verbose_name = _("Product Specification")
        verbose_name_plural = _("Product Specifications")

    def __str__(self):
        return self.name


class Product(models.Model):
    """
    The Product table contining all product items.
    """

    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    title = models.CharField(
        verbose_name=_("title"),
        help_text=_("Required"),
        max_length=255,
    )
    description = models.TextField(
        verbose_name=_("description"), help_text=_("Not Required"), blank=True
    )
    slug = models.SlugField(max_length=255)
    regular_price = models.DecimalField(
        verbose_name=_("Regular price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
    )
    discount_price = models.DecimalField(
        verbose_name=_("Discount price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
    )
    is_active = models.BooleanField(
        verbose_name=_("Product visibility"),
        help_text=_("Change product visibility"),
        default=True,
    )
    created_at = models.DateTimeField(
        _("Created at"), auto_now_add=True, editable=False
    )
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    users_wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_wishlist", blank=True)

    class Meta:
        ordering = ("-created_at",)
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.slug])

    def __str__(self):
        return self.title


class ProductSpecificationValue(models.Model):
    """
    The Product Specification Value table holds each of the
    products individual specification or bespoke features.
    """

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    specification = models.ForeignKey(ProductSpecification, on_delete=models.RESTRICT)
    value = models.CharField(
        verbose_name=_("value"),
        help_text=_("Product specification value (maximum of 255 words"),
        max_length=255,
    )

    class Meta:
        verbose_name = _("Product Specification Value")
        verbose_name_plural = _("Product Specification Values")

    def __str__(self):
        return self.value


class ProductImage(models.Model):
    """
    The Product Image table.
    """

    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="product_image"
    )
    image = models.ImageField(
        verbose_name=_("image"),
        help_text=_("Upload a product image"),
        upload_to="images/",
        default="images/default.png",
    )
    alt_text = models.CharField(
        verbose_name=_("Alturnative text"),
        help_text=_("Please add alturnative text"),
        max_length=255,
        null=True,
        blank=True,
    )
    is_feature = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Product Image")
        verbose_name_plural = _("Product Images")

apps/store/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView

from .models import Category, Product


class AllProducts(ListView):
    """ "Return products that are in stock"""

    template_name = "store/index.html"
    queryset = (
        Product.objects.all().prefetch_related("product_image").filter(is_active=True)
    )

    # some_product = queryset.first()
    # some_product.product_image.filter(is_active=True)
    context_object_name = "products"


class CategoryList(DetailView):
    """Return all the products of the selected category."""

    template_name = "store/category.html"

    def get_object(self):
        category_slug = self.kwargs.get("category_slug")
        return get_object_or_404(Category, slug=category_slug)

    def get_queryset(self):
        c_node = Category.objects.get(name=self.kwargs["category_slug"]).is_child_node()
        query_set = Product.objects.filter(
            category__in=Category.objects.get(
                name=self.kwargs["category_slug"]
            ).get_family()
            if not c_node
            else c_node
        )
        print(query_set)
        return query_set

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.get_object
        context["products"] = self.get_queryset
        return context


class ProductDetail(DetailView):
    template_name = "store/single.html"
    context_object_name = "product"

    def get_object(self):
        slug = self.kwargs.get("slug")
        return get_object_or_404(Product, slug=slug, is_active=True)

    def get_queryset(self):
        query_set = Product.objects.filter(
            category__in=Category.objects.get(name="django").get_descendants(
                include_self=True
            )
        )
        return query_set
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["wishlist"] = list(Product.objects.filter(users_wishlist=self.request.user))
        print(context['wishlist'])
        return context

templates/store/category.html
{% extends "../base.html" %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}

<div class="container" style="max-width: 1000px">
  <div class="col-12">
    <h1 class="h2">{{ category.name|title }}</h1>
  </div>
  <div class="col-12 d-flex justify-content-between">
    <div><b>Popular</b> products purchased</div>
  </div>
  <hr />
</div>
<div class="container">
  <div class="row">
    <div class="album">
      {% if not products %}
      <div class="col-12">There are currently no products active <a href="{% url 'store:store_home' %}">Home</a></div>
      {% else %}
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for product in products %}
        <div class="card border-0">
          {% for image_oj in product.product_image.all %}
          {% if image_oj.is_feature %}
          <img class="img-fluid" alt="{{image_oj.alt_text}}" src="{{ image_oj.image.url }}">
          {% endif %}
          {% endfor %}

          <div class="card-body px-0">
            <p class="card-text">
              <a class="text-dark text-decoration-none"
                href="{{ product.get_absolute_url }}">{{ product.title|slice:":50" }}...</a>
            </p>
            <div class="fw-bold">£{{product.regular_price}}</div>
          </div>
        </div>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

templates/store/index.html
{% extends "base.html" %}
{% block title %}Store - Low Prices in Books & more{% endblock %}
{% block content %}

<div class="container">
  <div class="alert alert-primary fw600 rounded-0 border-0 pb-3" role="alert">
    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-info-circle me-2"
      viewBox="0 0 16 16">
      <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
      <path
        d="M8.93 6.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
    </svg>
    COVID-19 - <u>Click here for our latest updates</u> on our stores, website and contact centre. Thank you for
    your patience and support.
  </div>
  <div class="container">
    <div class="row">
      <div class="album py-5">
        <div class="pb-3">
          <h1 class="h3">Popular</h1>
        </div>
        {% if not products %}
        <div class="col-12">There are currently no products active</div>
        {% else %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
          {% for product in products %}
          <div class="col">
            <div class="card border-0">
              <a href="{{ product.get_absolute_url }}">
              {% for image_oj in product.product_image.all %}
              {% if image_oj.is_feature %}
              <img class="img-fluid" alt="{{image_oj.alt_text}}" src="{{ image_oj.image.url }}" style='width:200px; height: 300px;'>
              {% endif %}
              {% endfor %}
              </a>

              <div class="card-body px-0">
                <p class="card-text">
                  <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">
                    {% if product.title|length >= 50 %}
                    {{ product.title|slice:":50" }}...
                    {% else %}
                    {{product.title}}
                    {% endif %}
                  </a>
                </p>
                <div class="fw-bold">£{{product.regular_price}}</div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        {% endif %}
      </div>
    </div>
  </div>

  {% endblock %}

templates/store/single.html
{% extends "../base.html" %}
{% load static %}
{% block stylesheet %}{% static 'store/css/store.css' %}{% endblock %}
{% block title %}
{% if product %}{{ product.title }}{% else %}Product{% endif %}
{% endblock %}
{% block content %}

<div class="container">
  {% if messages %}
  <div class="alert alert-warning alert-{{ message.tags }}" role="alert">
    {% for message in messages  %}
    {{message|safe}} - <a href="{% url "account:wishlist" %}" class="alert-link">Your Wishlist</a>.
    {% endfor %}
  </div>
  {% endif %}
  <div class="row g-3">
    <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
      <div class="d-grid gap-2">
        <div class="d-flex d-flex-inline justify-content-between">
          <div><span class="h3">£{{ product.regular_price }}</span>
            <p class="text-muted">includes tax</p>
          </div>
          <div>
            <label for="select">Qty</label>
            <select id="select" class="h6 store-select-dropdown">
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
            </select>
          </div>
        </div>
        <hr>
        <button type="button" id="add-button" value="{{product.id}}" class="btn btn-success fw500">Add to
          basket</button>
        {% if not product in wishlist %}
        <a href="{% url "account:user_wishlist" product.id  %}" class="btn btn-light fw500" role="button"
          aria-disabled="true">Add to Wish List</a>
        {% else %}
        <a href="{% url "account:user_wishlist" product.id  %}" class="btn btn-light fw500" role="button"
          aria-disabled="true">Remove from Wish List</a>
        {% endif %}
      </div>
    </div>
    <div class="col-md-7 col-lg-7 p-0">
      <div class="card mb-3 border-0">
        <div class="row g-0">
          <div class="col-md-12">
            <div class="card-body p-1">
              <h1 class="mb-0 h2 pe-4 pb-4">{{ product.title }}</h1>
              <div class="bg-light">

                {% for image_obj in product.product_image.all %}
                {% if image_obj.is_feature %}
                <img class="img-fluid mx-auto d-block" width="250px" alt="Responsive image"
                  src="{{ image_obj.image.url }}" alt="{{ image_obj.image.alt_text }}">
                {% else %}
                <img class="img-pfluid d-block-inline pt-3" width="50px" alt="Responsive image"
                  src="{{ image_obj.image.url }}" alt="{{ image_obj.image.alt_text }}">
                {% endif %}
                {% endfor %}

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).on('click', '#add-button', function (e) {
    e.preventDefault();
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_add" %}',
      data: {
        productid: $('#add-button').val(),
        productqty: $('#select option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        document.getElementById("basket-qty").innerHTML = json.qty
      },
      error: function (xhr, errmsg, err) {}
    });
  })
</script>

{% endblock %}

templates/store/tr.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Payment handler</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Payment handler</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarScroll">
                <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>

                </ul>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% if deposit %}
                    <li class="nav-item deposit_border">Total Deposit: {{ deposit.amount }}$</li>
                    {% else %}
                    <li class="nav-item deposit_border">Total Deposit: 0.00$</li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container" style="margin-top: 50px;">
        <table class="table table-dark table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">name</th>
                    <th scope="col">description</th>
                    <th scope="col">purchased at</th>
                    <th scope="col">price</th>
                    <th scope="col">category</th>
                </tr>
            </thead>
            <tbody>
                {% if elements %}
                {% for element in elements %}
                <tr>
                    <th scope="row">{{element.id}}</th>
                    <td>{{element.name}}</td>
                    <td>{{element.description}}</td>
                    <td>{{element.created_at}}</td>
                    <td>{{element.price}}</td>
                    <td>{{element.category.name}}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <th scope="row">-</th>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                </tr>
                {% endif %}
            </tbody>
        </table>
        <div class="col">
            <a href="#" class="text-reset text-decoration-none" role="button" style="max-width: 540px;">
                <div class="card mb-3 h-100" style="border: dashed 2px #ccc;">
                    <div class="row g-0 h-100">
                        <div class="col-12" style="min-height:100px">
                            <div class="card-body text-center position-absolute top-50 start-50 translate-middle">
                                <svg style="color:#ccc;" xmlns="http://www.w3.org/2000/svg" width="60" height="60"
                                    fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                                    <path
                                        d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                                </svg>
                                <h1 class="h5">Add Address</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>
</body>

</html>